---
- name: Wait until mysqld starts
  pause: 
    seconds: 40
- name: Add nodes
  docker_container:
      name: "{{ item }}"
      image: "percona/percona-xtradb-cluster:{{ mysql_image_version }}"
      hostname: "{{ item }}"
      detach: yes
      #volumes:
      #  - "{{ role_path }}/my.cnf.{{ item }}:/etc/my.cnf"
      networks:
        - name: "{{ docker_network_name }}"
      env:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        CLUSTER_NAME: "dani-pxc-docker"
        CLUSTER_JOIN: "pxc1"
#  with_sequence: start=1 end="{{ servers }}" format=mysql%01x
#  command: >
#    docker exec {{ item }} bash -c "MYSQL_PWD=; mysql -uroot -e \"change master to master_host='mysql1', master_user='root', master_log_file='mysql-bin.000001', master_log_pos = 4; start slave\""
  with_sequence: start={{2 if servers|int == 3 else servers }} end="{{ servers }}" format=pxc%01x

